<?php
// Variables
return [
  "creatorName" => "ThemeSelection",
  "creatorUrl" => "https://themeselection.com",
  "templateName" => "Sneat",
  "templateSuffix" => "Laravel Bootstrap Starter Kit",
  "templateVersion" => "1.0.0",
  "templateFree" => true,
  "templateDescription" => "Laravel 12 Starter Kit with Bootstrap 5 – Powerful template for developers, offering clean code and seamless integration with Bootstrap 5 components.",
  "templateKeyword" => "laravel 12 starter kit, laravel bootstrap 5, bootstrap 5 starter kit, laravel bootstrap template, developer-friendly dashboard template",
  "licenseUrl" => "https://themeselection.com/license/",
  "livePreview" => "https://demos.themeselection.com/sneat-bootstrap-html-laravel-admin-template-free/demo/",
  "productPage" => "https://themeselection.com/item/sneat-dashboard-free-laravel/",
  "ogTitle" => "Laravel Bootstrap Starter Kit by ThemeSelection",
  "ogType" => "product",
  "ogImage" => "https://github-production-user-asset-6210df.s3.amazonaws.com/61959920/427390692-8befef61-cad6-4f18-a6b5-d4ce621b8eb4.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAVCODYLSA53PQK4ZA%2F20250327%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250327T080458Z&X-Amz-Expires=300&X-Amz-Signature=1c26218a52448caf7e50e8d05c7267eec9595cb7d58b9df9fac616d29289dfab&X-Amz-SignedHeaders=host",
  "support" => "https://github.com/themeselection/sneat-bootstrap-laravel-livewire-starter-kit/issues",
  "moreThemes" => "https://themeselection.com/",
  "documentation" => "https://demos.themeselection.com/sneat-bootstrap-html-admin-template/documentation",
  "repository" => "https://github.com/themeselection/sneat-bootstrap-laravel-livewire-starter-kit",
  "gitRepo" => "https://github.com/themeselection/sneat-bootstrap-laravel-livewire-starter-kit.git",
  "gitRepoAccess" => "https://tools.themeselection.com/github/github-access",
  "githubFreeUrl" => "https://github.com/themeselection",
  "facebookUrl" => "https://www.facebook.com/ThemeSelections/",
  "twitterUrl" => "https://x.com/Theme_Selection",
  "githubUrl" => "https://github.com/themeselection",
  "dribbbleUrl" => "https://dribbble.com/themeselection",
  "instagramUrl" => "https://www.instagram.com/themeselection/"
];
